export { default as Home } from './home.svg'
export { default as Chats } from './message-circle.svg'
export { default as Payment } from './dollar-sign.svg'
export { default as Profile } from './user.svg'
export { default as ChevronRight } from './chevron-right.svg'
export { default as ChevronLeft } from './chevron-left.svg'
