require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'
# platform :ios, '11.0'

target 'Chat' do
  # use_unimodules!
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'

  use_react_native!(:path => config["reactNativePath"])

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"


  # target 'ChatTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # # Enables Flipper.
  # #
  # # Note that if you have use_frameworks! enabled, Flipper will not work and
  # # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

# target 'Chat-tvOS' do
#   # Pods for Chat-tvOS

#   target 'Chat-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10'
    end
  end
end